-- Drop the temporary 'category' column from the posts table
alter table posts
drop column if exists category;

-- Create the categories table
create table categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table categories enable row level security;
create policy "Categories are viewable by everyone." on categories for select using (true);
create policy "Admins can insert categories." on categories for insert with check (
  (select "role" from profiles where id = auth.uid()) = 'ADM'
);
create policy "Admins can update categories." on categories for update using (
  (select "role" from profiles where id = auth.uid()) = 'ADM'
);
create policy "Admins can delete categories." on categories for delete using (
  (select "role" from profiles where id = auth.uid()) = 'ADM'
);

-- Create the post_categories join table
create table post_categories (
  post_id bigint references public.posts on delete cascade not null,
  category_id bigint references public.categories on delete cascade not null,
  primary key (post_id, category_id)
);

alter table post_categories enable row level security;
create policy "Post-category relationships are viewable by everyone." on post_categories for select using (true);
create policy "Users can insert categories for their own posts." on post_categories for insert with check (
  auth.uid() = (select user_id from posts where id = post_id)
);
create policy "Users can delete categories from their own posts." on post_categories for delete using (
  auth.uid() = (select user_id from posts where id = post_id)
);


-- Create the likes table
create table likes (
  user_id uuid references public.profiles on delete cascade not null,
  post_id bigint references public.posts on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, post_id)
);

alter table likes enable row level security;
create policy "Users can view all likes." on likes for select using (true);
create policy "Users can insert their own likes." on likes for insert with check (auth.uid() = user_id);
create policy "Users can delete their own likes." on likes for delete using (auth.uid() = user_id);

-- Trigger function to increment/decrement likes_count on posts table
create function public.handle_like_change()
returns trigger as $$
begin
  if (TG_OP = 'INSERT') then
    update public.posts set likes_count = likes_count + 1 where id = new.post_id;
  elsif (TG_OP = 'DELETE') then
    update public.posts set likes_count = likes_count - 1 where id = old.post_id;
  end if;
  return null;
end;
$$ language plpgsql security definer;

create trigger on_like_created
  after insert on public.likes
  for each row execute procedure public.handle_like_change();

create trigger on_like_deleted
  after delete on public.likes
  for each row execute procedure public.handle_like_change();
