create table post_images (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts on delete cascade not null,
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table post_images enable row level security;

create policy "Post images are viewable by everyone." on post_images
  for select using (true);

create policy "Users can insert images for their own posts." on post_images
  for insert with check (
    auth.uid() = (select user_id from posts where id = post_id)
  );

create policy "Users can delete images from their own posts." on post_images
  for delete using (
    auth.uid() = (select user_id from posts where id = post_id)
  );

-- Remove image_url from posts table as it is now in post_images
alter table posts
drop column if exists image_url;
