-- Followers System
create table followers (
  follower_id uuid references public.profiles on delete cascade not null,
  following_id uuid references public.profiles on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (follower_id, following_id)
);

alter table followers enable row level security;

create policy "Users can select all follower relationships." on followers
  for select using (true);

create policy "Users can insert their own follow relationships." on followers
  for insert with check (auth.uid() = follower_id);

create policy "Users can delete their own follow relationships." on followers
  for delete using (auth.uid() = follower_id);


-- Posts System
create table posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles on delete cascade not null,
  title text,
  content text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table posts enable row level security;

create policy "Users can select all posts." on posts
  for select using (true);

create policy "Users can insert their own posts." on posts
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own posts." on posts
  for update using (auth.uid() = user_id);

create policy "Users can delete their own posts." on posts
  for delete using (auth.uid() = user_id);
